import { GalleryImage } from '@/types';

export const galleryImages: GalleryImage[] = [
  {
    id: '1',
    src: '/images/gallery-raft-sunset.jpg',
    alt: 'Saunalautta auringonlaskussa',
    caption: 'Kesän kauneimmat hetket merellä',
    category: 'boats',
  },
  {
    id: '2',
    src: '/images/gallery-aalto-raft.jpeg',
    alt: 'Aalto-saunalautta',
    caption: 'Aalto on tilava ja viihtyisä',
    category: 'boats',
  },
  {
    id: '3',
    src: '/images/gallery-sauna-interior.jpg',
    alt: 'Saunan sisätilat',
    caption: 'Perinteinen puulämmitteinen sauna',
    category: 'sauna',
  },
  {
    id: '4',
    src: '/images/gallery-sauna-steam.jpg',
    alt: 'Löylyt hehkuvat',
    caption: 'Aidot löylyt puukiukaasta',
    category: 'sauna',
  },
  {
    id: '5',
    src: '/images/gallery-sauna-group.jpg',
    alt: 'Saunojia löylyhuoneessa',
    caption: 'Yhteinen saunakokemus',
    category: 'experience',
  },
  {
    id: '6',
    src: '/images/gallery-deck-view.jpg',
    alt: 'Näkymä kannelta',
    caption: 'Merinäkymät Kalkkihiekantorilta',
    category: 'experience',
  },
  {
    id: '7',
    src: '/images/gallery-deck-chairs.jpeg',
    alt: 'Kansituoleja',
    caption: 'Rentoutumista kannella',
    category: 'experience',
  },
  {
    id: '8',
    src: '/images/gallery-bbq.jpg',
    alt: 'Grillausta kannelle',
    caption: 'Ruokailu merellä',
    category: 'summer',
  },

  {
    id: '10',
    src: '/images/gallery-sunset-dock.jpeg',
    alt: 'Auringonlasku laiturilla',
    caption: 'Illan viimeiset säteet',
    category: 'summer',
  },
  {
    id: '11',
    src: '/images/gallery-ice-swimming.jpg',
    alt: 'Talviuinti',
    caption: 'Avantouinti talvisin',
    category: 'winter',
  },
  {
    id: '12',
    src: '/images/gallery-winter-swim.jpg',
    alt: 'Talvinen saunominen',
    caption: 'Talvi ei estä saunomista',
    category: 'winter',
  },
  {
    id: '13',
    src: '/images/gallery-sauna-bench.jpg',
    alt: 'Laude näkymä',
    caption: 'Perinteiset lauteet',
    category: 'sauna',
  },
  {
    id: '14',
    src: '/images/gallery-sauna-stove.jpg',
    alt: 'Lautta hämärällä',
    caption: 'Lautta hämärällä',
    category: 'sauna',
  },
  {
    id: '15',
    src: '/images/gallery-crew.jpeg',
    alt: 'Tiimi',
    caption: 'Hyvän Tuulen tiimi',
    category: 'experience',
  },
  {
    id: '16',
    src: '/images/gallery-aalto-misty.jpeg',
    alt: 'Aalto sumuisessa säässä',
    caption: 'Tunnelmallinen aamu Aallolla',
    category: 'boats',
  },
  {
    id: '17',
    src: '/images/gallery-aalto-pukkari.jpeg',
    alt: 'Aallon pukuhuone',
    caption: 'Tilava pukuhuone',
    category: 'boats',
  },
  {
    id: '18',
    src: '/images/gallery-aalto-sohva.jpeg',
    alt: 'Aallon oleskelutila',
    caption: 'Viihtyisä oleskelutila',
    category: 'boats',
  },
  {
    id: '19',
    src: '/images/gallery-avanto-woman.jpg',
    alt: 'Avantouinti',
    caption: 'Raikas pulaus avannossa',
    category: 'winter',
  },
  {
    id: '20',
    src: '/images/gallery-cozy-bench.jpg',
    alt: 'Aallon grilli',
    caption: 'Aallon grilli',
    category: 'experience',
  },
  {
    id: '21',
    src: '/images/gallery-helm.jpeg',
    alt: 'Ruori',
    caption: 'Kapteenin paikalta',
    category: 'boats',
  },
  {
    id: '22',
    src: '/images/gallery-jetski.jpeg',
    alt: 'Vesijetti',
    caption: 'Vauhdikasta menoa',
    category: 'summer',
  },
  {
    id: '23',
    src: '/images/gallery-led-sauna.jpg',
    alt: 'Sauna valaistuksella',
    caption: 'Tunnelmallinen sauna',
    category: 'sauna',
  },
  {
    id: '24',
    src: '/images/gallery-raft-foggy.jpg',
    alt: 'Saunalautta sumussa',
    caption: 'Mystinen aamutunnelma',
    category: 'boats',
  },
  {
    id: '25',
    src: '/images/gallery-sauna-guy.jpg',
    alt: 'Saunoja löylyissä',
    caption: 'Aidot löylyt',
    category: 'sauna',
  },
  {
    id: '26',
    src: '/images/gallery-sauna-smoke.jpg',
    alt: 'Saunan savu',
    caption: 'Tulisijan lämpöä',
    category: 'sauna',
  },
  {
    id: '27',
    src: '/images/gallery-sauna-woman.jpg',
    alt: 'Saunoja nauttimassa',
    caption: 'Rentoutumista löylyissä',
    category: 'sauna',
  },
  {
    id: '28',
    src: '/images/gallery-sea-view.jpg',
    alt: 'Merinäkymä',
    caption: 'Upeat merinäkymät',
    category: 'experience',
  },
  {
    id: '29',
    src: '/images/gallery-sunset-raft.jpeg',
    alt: 'Auringonlasku lautalla',
    caption: 'Kultainen hetki merellä',
    category: 'summer',
  },
  {
    id: '30',
    src: '/images/gallery-sup-boards.jpeg',
    alt: 'Sup-laudat',
    caption: 'Sup-lautailua saaristossa',
    category: 'summer',
  },
  {
    id: '31',
    src: '/images/gallery-virta-deck.jpeg',
    alt: 'Virran kansi',
    caption: 'Virran tilava kansi',
    category: 'boats',
  },
  {
    id: '32',
    src: '/images/gallery-virta-kall.jpg',
    alt: 'Virta kallioilla',
    caption: 'Virta luonnon keskellä',
    category: 'boats',
  },
  {
    id: '33',
    src: '/images/gallery-weber-view.jpg',
    alt: 'Grillinäkymä',
    caption: 'Weber-grilli kuumana',
    category: 'experience',
  },
  {
    id: '34',
    src: '/images/gallery-winter-dock.jpg',
    alt: 'Talvinen laituri',
    caption: 'Kaunis talvipäivä',
    category: 'winter',
  },
  {
    id: '35',
    src: '/images/gallery-winter-sunset.jpeg',
    alt: 'Talvinen auringonlasku',
    caption: 'Talven taikaa',
    category: 'winter',
  },
];

export const galleryCategories = [
  { id: 'all', label: 'Kaikki' },
  { id: 'boats', label: 'Saunalautat' },
  { id: 'sauna', label: 'Sauna' },
  { id: 'experience', label: 'Elämykset' },
  { id: 'summer', label: 'Kesä' },
  { id: 'winter', label: 'Talvi' },
] as const;
