import { GalleryImage } from '@/types';
import type { Locale } from './pages';

// alt/caption hold the Finnish texts; altEn/captionEn their English variants.
// Use getGalleryImages(locale) / getGalleryCategories(locale) to get
// locale-appropriate strings.
type LocalizedGalleryImage = GalleryImage & { altEn: string; captionEn?: string };

const images: LocalizedGalleryImage[] = [
  {
    id: '1',
    src: '/images/gallery-raft-sunset.webp',
    alt: 'Saunalautta auringonlaskussa',
    altEn: 'Sauna boat at sunset',
    caption: 'Kesän kauneimmat hetket merellä',
    captionEn: 'The most beautiful summer moments at sea',
    category: 'boats',
  },
  {
    id: '2',
    src: '/images/gallery-aalto-raft.webp',
    alt: 'Aalto-saunalautta',
    altEn: 'Aalto sauna boat',
    caption: 'Aalto on tilava ja viihtyisä',
    captionEn: 'Aalto is spacious and cozy',
    category: 'boats',
  },
  {
    id: '3',
    src: '/images/gallery-sauna-interior.webp',
    alt: 'Saunan sisätilat',
    altEn: 'Sauna interior',
    caption: 'Perinteinen puulämmitteinen sauna',
    captionEn: 'Traditional wood-fired sauna',
    category: 'sauna',
  },
  {
    id: '4',
    src: '/images/gallery-sauna-steam.webp',
    alt: 'Löylyt hehkuvat',
    altEn: 'The löyly is glowing hot',
    caption: 'Aidot löylyt puukiukaasta',
    captionEn: 'Authentic löyly from a wood-fired heater',
    category: 'sauna',
  },
  {
    id: '5',
    src: '/images/gallery-sauna-group.webp',
    alt: 'Saunojia löylyhuoneessa',
    altEn: 'Bathers in the sauna room',
    caption: 'Yhteinen saunakokemus',
    captionEn: 'A shared sauna experience',
    category: 'experience',
  },
  {
    id: '6',
    src: '/images/gallery-deck-view.webp',
    alt: 'Näkymä kannelta',
    altEn: 'View from the deck',
    caption: 'Merinäkymät Kalkkihiekantorilta',
    captionEn: 'Sea views from Kalkkihiekantori',
    category: 'experience',
  },
  {
    id: '7',
    src: '/images/gallery-deck-chairs.webp',
    alt: 'Kansituoleja',
    altEn: 'Deck chairs',
    caption: 'Rentoutumista kannella',
    captionEn: 'Relaxing on the deck',
    category: 'experience',
  },
  {
    id: '8',
    src: '/images/gallery-bbq.webp',
    alt: 'Grillausta kannelle',
    altEn: 'Grilling on deck',
    caption: 'Ruokailu merellä',
    captionEn: 'Dining at sea',
    category: 'summer',
  },

  {
    id: '10',
    src: '/images/gallery-sunset-dock.webp',
    alt: 'Auringonlasku laiturilla',
    altEn: 'Sunset at the pier',
    caption: 'Illan viimeiset säteet',
    captionEn: 'The last rays of the evening',
    category: 'summer',
  },
  {
    id: '11',
    src: '/images/gallery-ice-swimming.webp',
    alt: 'Talviuinti',
    altEn: 'Winter swimming',
    caption: 'Avantouinti talvisin',
    captionEn: 'Ice swimming in winter',
    category: 'winter',
  },
  {
    id: '12',
    src: '/images/gallery-winter-swim.webp',
    alt: 'Talvinen saunominen',
    altEn: 'Winter sauna',
    caption: 'Talvi ei estä saunomista',
    captionEn: 'Winter does not stop sauna',
    category: 'winter',
  },
  {
    id: '13',
    src: '/images/gallery-sauna-bench.webp',
    alt: 'Laude näkymä',
    altEn: 'Bench view',
    caption: 'Perinteiset lauteet',
    captionEn: 'Traditional benches',
    category: 'sauna',
  },
  {
    id: '14',
    src: '/images/gallery-sauna-stove.webp',
    alt: 'Lautta hämärällä',
    altEn: 'The boat at dusk',
    caption: 'Lautta hämärällä',
    captionEn: 'The boat at dusk',
    category: 'sauna',
  },
  {
    id: '15',
    src: '/images/gallery-crew.webp',
    alt: 'Tiimi',
    altEn: 'The team',
    caption: 'Hyvän Tuulen tiimi',
    captionEn: 'The Hyvän Tuulen team',
    category: 'experience',
  },
  {
    id: '16',
    src: '/images/gallery-aalto-misty.webp',
    alt: 'Aalto sumuisessa säässä',
    altEn: 'Aalto in misty weather',
    caption: 'Tunnelmallinen aamu Aallolla',
    captionEn: 'An atmospheric morning on Aalto',
    category: 'boats',
  },
  {
    id: '17',
    src: '/images/gallery-aalto-pukkari.webp',
    alt: 'Aallon pukuhuone',
    altEn: "Aalto's changing room",
    caption: 'Tilava pukuhuone',
    captionEn: 'Spacious changing room',
    category: 'boats',
  },
  {
    id: '18',
    src: '/images/gallery-aalto-sohva.webp',
    alt: 'Aallon oleskelutila',
    altEn: "Aalto's lounge area",
    caption: 'Viihtyisä oleskelutila',
    captionEn: 'Cozy lounge area',
    category: 'boats',
  },
  {
    id: '19',
    src: '/images/gallery-avanto-woman.webp',
    alt: 'Avantouinti',
    altEn: 'Ice swimming',
    caption: 'Raikas pulaus avannossa',
    captionEn: 'A refreshing dip in the ice hole',
    category: 'winter',
  },
  {
    id: '20',
    src: '/images/gallery-cozy-bench.webp',
    alt: 'Aallon grilli',
    altEn: "Aalto's grill",
    caption: 'Aallon grilli',
    captionEn: "Aalto's grill",
    category: 'experience',
  },
  {
    id: '21',
    src: '/images/gallery-helm.webp',
    alt: 'Ruori',
    altEn: 'The helm',
    caption: 'Kapteenin paikalta',
    captionEn: "From the captain's seat",
    category: 'boats',
  },
  {
    id: '22',
    src: '/images/gallery-jetski.webp',
    alt: 'Vesijetti',
    altEn: 'Jet ski',
    caption: 'Vauhdikasta menoa',
    captionEn: 'Fast-paced action',
    category: 'summer',
  },
  {
    id: '23',
    src: '/images/gallery-led-sauna.webp',
    alt: 'Sauna valaistuksella',
    altEn: 'Sauna with lighting',
    caption: 'Tunnelmallinen sauna',
    captionEn: 'Atmospheric sauna',
    category: 'sauna',
  },
  {
    id: '24',
    src: '/images/gallery-raft-foggy.webp',
    alt: 'Saunalautta sumussa',
    altEn: 'Sauna boat in the fog',
    caption: 'Mystinen aamutunnelma',
    captionEn: 'A mystical morning mood',
    category: 'boats',
  },
  {
    id: '25',
    src: '/images/gallery-sauna-guy.webp',
    alt: 'Saunoja löylyissä',
    altEn: 'Bather in the löyly',
    caption: 'Aidot löylyt',
    captionEn: 'Authentic löyly',
    category: 'sauna',
  },
  {
    id: '26',
    src: '/images/gallery-sauna-smoke.webp',
    alt: 'Saunan savu',
    altEn: 'Sauna smoke',
    caption: 'Tulisijan lämpöä',
    captionEn: 'Warmth from the fireplace',
    category: 'sauna',
  },
  {
    id: '27',
    src: '/images/gallery-sauna-woman.webp',
    alt: 'Saunoja nauttimassa',
    altEn: 'Bather enjoying the sauna',
    caption: 'Rentoutumista löylyissä',
    captionEn: 'Relaxing in the löyly',
    category: 'sauna',
  },
  {
    id: '28',
    src: '/images/gallery-sea-view.webp',
    alt: 'Merinäkymä',
    altEn: 'Sea view',
    caption: 'Upeat merinäkymät',
    captionEn: 'Stunning sea views',
    category: 'experience',
  },
  {
    id: '29',
    src: '/images/gallery-sunset-raft.webp',
    alt: 'Auringonlasku lautalla',
    altEn: 'Sunset on the boat',
    caption: 'Kultainen hetki merellä',
    captionEn: 'A golden moment at sea',
    category: 'summer',
  },
  {
    id: '30',
    src: '/images/gallery-sup-boards.webp',
    alt: 'Sup-laudat',
    altEn: 'SUP boards',
    caption: 'Sup-lautailua saaristossa',
    captionEn: 'SUP boarding in the archipelago',
    category: 'summer',
  },
  {
    id: '31',
    src: '/images/gallery-virta-deck.webp',
    alt: 'Virran kansi',
    altEn: "Virta's deck",
    caption: 'Virran tilava kansi',
    captionEn: "Virta's spacious deck",
    category: 'boats',
  },
  {
    id: '32',
    src: '/images/gallery-virta-kall.webp',
    alt: 'Virta kallioilla',
    altEn: 'Virta by the cliffs',
    caption: 'Virta luonnon keskellä',
    captionEn: 'Virta in the middle of nature',
    category: 'boats',
  },
  {
    id: '33',
    src: '/images/gallery-weber-view.webp',
    alt: 'Grillinäkymä',
    altEn: 'Grill view',
    caption: 'Weber-grilli kuumana',
    captionEn: 'Weber grill hot and ready',
    category: 'experience',
  },
  {
    id: '34',
    src: '/images/gallery-winter-dock.webp',
    alt: 'Talvinen laituri',
    altEn: 'Wintery pier',
    caption: 'Kaunis talvipäivä',
    captionEn: 'A beautiful winter day',
    category: 'winter',
  },
  {
    id: '35',
    src: '/images/gallery-winter-sunset.webp',
    alt: 'Talvinen auringonlasku',
    altEn: 'Winter sunset',
    caption: 'Talven taikaa',
    captionEn: 'Winter magic',
    category: 'winter',
  },
  {
    id: '36',
    src: '/images/gallery-sauna-group-new.webp',
    alt: 'Saunojia löylyhuoneessa',
    altEn: 'Bathers in the sauna room',
    caption: 'Yhteinen saunakokemus',
    captionEn: 'A shared sauna experience',
    category: 'sauna',
  },
  {
    id: '37',
    src: '/images/gallery-sauna-woman-new.webp',
    alt: 'Saunoja nauttimassa',
    altEn: 'Bather enjoying the sauna',
    caption: 'Rentoutumista löylyissä',
    captionEn: 'Relaxing in the löyly',
    category: 'sauna',
  },
  {
    id: '38',
    src: '/images/gallery-aalto-raft-new.webp',
    alt: 'Aalto-saunalautta',
    altEn: 'Aalto sauna boat',
    caption: 'Aalto merellä',
    captionEn: 'Aalto at sea',
    category: 'boats',
  },
  {
    id: '39',
    src: '/images/gallery-aalto-misty-new.webp',
    alt: 'Aalto sumuisessa säässä',
    altEn: 'Aalto in misty weather',
    caption: 'Tunnelmallinen aamu Aallolla',
    captionEn: 'An atmospheric morning on Aalto',
    category: 'boats',
  },
  {
    id: '40',
    src: '/images/gallery-aalto-7547.webp',
    alt: 'Aalto-saunalautta',
    altEn: 'Aalto sauna boat',
    caption: 'Aallon kansi',
    captionEn: "Aalto's deck",
    category: 'boats',
  },
];

export const getGalleryImages = (locale: Locale = 'fi'): GalleryImage[] =>
  images.map(({ altEn, captionEn, ...image }) =>
    locale === 'en' ? { ...image, alt: altEn, caption: captionEn } : image
  );

export const galleryImages: GalleryImage[] = getGalleryImages('fi');

export const getGalleryCategories = (locale: Locale = 'fi') =>
  locale === 'en'
    ? ([
        { id: 'all', label: 'All' },
        { id: 'boats', label: 'Sauna boats' },
        { id: 'sauna', label: 'Sauna' },
        { id: 'experience', label: 'Experiences' },
        { id: 'summer', label: 'Summer' },
        { id: 'winter', label: 'Winter' },
      ] as const)
    : ([
        { id: 'all', label: 'Kaikki' },
        { id: 'boats', label: 'Saunalautat' },
        { id: 'sauna', label: 'Sauna' },
        { id: 'experience', label: 'Elämykset' },
        { id: 'summer', label: 'Kesä' },
        { id: 'winter', label: 'Talvi' },
      ] as const);

export const galleryCategories = getGalleryCategories('fi');
